### ISSUE TITLE
Add plugin support

### ISSUE THREAD

**Issue by MacroPower** [MacroPower/kat#23]
I should be able to add "plugins" that are available to execute on a given keybind.

```yaml
commands:
  - match: ...
    plugins:
      validate:
        description: validate the things
        keys: [{code: v}]
        command: ...
        args: []
```
