### ISSUE TITLE
Add support for configuration profiles

### ISSUE THREAD

**Issue by MacroPower** [MacroPower/kat#24]
e.g.,

```yaml
profiles:
  foo:
    ui:
      theme: onedark
      compact: false
      word-wrap: false
  bar:
    ui:
      theme: tokyonight-storm
      compact: true
      word-wrap: true
```

```
kat -p home
```

Possibly also allow setting a default profile on match:

```yaml
commands:
  - match: .*/Chart\.ya?ml$
    profile: foo
    # ...
  - match: .*/kustomization\.ya?ml$
    profile: bar
    # ...
```
